plugins:
  - jekyll-seo-tag
title: satin gaux
description: sachin sharma . A computer science student at IIIT.
url: satingaux.github.io
auther: sachin sharma
social:
  name: Satin Gaux
  links:
    - https://twitter.com/satingaux
    - https://www.linkedin.com/in/satingaux
    - https://github.com/satingaux
